name: Simple Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build static site
      run: |
        echo "Building static site..."
        
        # Ensure minified CSS exists and is up to date
        if [ ! -f "static/styles.min.css" ]; then
          sed 's/\/\*.*\*\///g; s/  */ /g; s/; /;/g' static/styles.css > static/styles.min.css
        fi
        
        # Ensure index.html uses minified CSS
        if ! grep -q "styles.min.css" index.html; then
          sed 's/styles\.css/styles.min.css/g' index.html > index.tmp.html
          mv index.tmp.html index.html
        fi
        
        echo "✅ Static site built successfully"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: lukaslondono77/flor_animada
        publish_dir: ./
        exclude_assets: |
          .github/
          app.py
          requirements.txt
          *.md
